# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Clear Solar
tagline: Clear Solar, increasing your panels efficiency!  # it will display as the sub-title
description: >- # this means to ignore newlines until "baseurl:"
  Here at Clear Solar we are the number 1 solar panel cleaning company in Ireland

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Brand
logo: "/assets/images/logos/logo.png"
logo_2: "/assets/images/logos/logo.png"
favicon: "/assets/images/favicon/favicon.ico"

twitter_username: jekyllrb
github_username:  jekyll
github:
  repository_url: "https://github.com/username/repository" # replace with your GitHub repo URL

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 10 # Amount of posts to show on paginated pages
timezone: "Europe/Dublin" # Timezone for your site
locale: "en-IE" # Locale for your site
lang: en

#site wide author
author:
  name: Your Name
  email: your-email@example.com

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: your_full_name
  email: example@domain.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/username # change to your twitter homepage
    - https://github.com/username # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  #- jekyll-github-metadata
  - jekyll-auto-image
  - jekyll-admin
  - jekyll-assets

# Tag Page
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Jekyll Archives
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

# Pagination
paginate_path: "/page:num/"

# Search
simple_search:
  search_fields:
    - title
    - tags
    - content

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Assets
assets:
  sources:
    - _assets/css
    - _assets/js

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext
  authors:
    output: true
  linkcollection:
    output: true
  nav:
    output: false
  tabs:
    output: true
    sort_by: order
  news:
    output: true
    permalink: /news/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_authors"
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "_linkcollection"
      type: "linkcollection"
    values:
      layout: "link"
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/